### ISSUE TITLE
DiscordSRV placeholders updated & ecloud

### ISSUE THREAD

**Issue by Vankka** [help-chat/PlaceholderAPI#1]
**What page should be changed?**  

https://github.com/help-chat/PlaceholderAPI/wiki/Placeholders#discordsrv

**What new value?**  

https://www.spigotmc.org/wiki/placeholderapi-plugin-placeholders-page-2/#discordsrv
Also on ecloud: https://api.extendedclip.com/expansions/discordsrv/

**Comment by Andre601** [comment]
Updated the placeholders.
Sorry for the delay

**Comment by Vankka** [comment]
@Andre601 could you also add the download link as the expansion is on ecloud? thanks

**Comment by Andre601** [comment]
done
