### ISSUE TITLE
Donations Holograms on the list of plugins

### ISSUE THREAD

**Issue by filoghost** [help-chat/PlaceholderAPI#10]
### Type
> What kind of request is this? (Multiple selections possible)

- [ ] New expansion providing placeholders.
- [x] New plugin providing placeholders.
- [ ] New plugin supporting PlaceholderAPI.

### Plugin
> What is the name of the plugin/expansion?
> Provide also a link to it.

Donations Holograms https://www.spigotmc.org/resources/donations-holograms.1956/

### Placeholders/others
> What are the new placeholders/Any additional info?

%donationsHolograms_percentage%
%donationsHolograms_progressBar%
%donationsHolograms_received%
%donationsHolograms_goal%

**Comment by Andre601** [comment]
Added it to the [placeholder list](/help-chat/PlaceholderAPI/wiki/Placeholders#donations-holograms)

Thank you for supporting PlaceholderAPI!
