### ISSUE TITLE
Plugin KP-PVP placeholders list

### ISSUE THREAD

**Issue by RAFAELESPADA** [help-chat/PlaceholderAPI#11]
### Type
> What kind of request is this? (Multiple selections possible)

- [ ] New expansion providing placeholders.
- [X] New plugin providing placeholders.
- [ ] New plugin supporting PlaceholderAPI.

### Plugin
> What is the name of the plugin/expansion?
KP-PVP
> Provide also a link to it.

https://www.spigotmc.org/resources/kp-pvp-the-ultimate-kitpvp-plugin.50969/

### Placeholders/others
> What are the new placeholders/Any additional info?

%kp-pvp_player_kills% - Returns the player kills
%kp-pvp_player_deaths% - Returns the player deaths
%kp-pvp_player_coins% - Returns the player coins
%kp-pvp_player_streak% - Returns the player kill streak
%kp-pvp_player_is_on_kitpvp% Returns Yes if the player are on kitpvp and returns No if he are not in kitpvp
%kp-pvp_players_count_total% - Returns the total players that are on kitpvp
%kp-pvp_player_kit% - Returns the player actual used kit

**Comment by Andre601** [comment]
[Added the placeholders](/help-chat/PlaceholderAPI/wiki/Placeholders#kp-pvp)

Thank you for supporting PlaceholderAPI.
