### ISSUE TITLE
Add new plugins to supported ones.

### ISSUE THREAD

**Issue by MrIvanPlays** [help-chat/PlaceholderAPI#12]
### Type
> What kind of request is this? (Multiple selections possible)

- [ ] New expansion providing placeholders.
- [x] New plugin providing placeholders.
- [ ] New plugin supporting PlaceholderAPI.

### Plugin
> What is the name of the plugin/expansion?
> Provide also a link to it.

AnnouncementsEverywhere -> https://www.spigotmc.org/resources/announcementseverywhere-1-9-1-13-2.59510/
UltraChatFormat -> https://www.spigotmc.org/resources/ultrachatformat-1-8-1-13-2.57929/
RankedHelp -> https://www.spigotmc.org/resources/rankedhelp-1-8-1-13-2.61919/

### Placeholders/others
> What are the new placeholders/Any additional info?

No new placeholders from these 3. 
The announcements plugin supports also bungeecord, which bungeecord doesn't support placeholderapi (coz placeholderapi doesn't have bungeeside support obvious).

**Comment by Andre601** [comment]
Your request is more the last option in the Type-section:
- [ ] New plugin supporting PlaceholderAPI.

I've added the plugins, but use the right type next time ;)

**Comment by MrIvanPlays** [comment]
Wow didnt noticed that. Thanks
