### ISSUE TITLE
Placeholders is broken

### ISSUE THREAD

**Issue by a7ssan** [help-chat/PlaceholderAPI#2]
look : https://pastebin.com/WmGxeKfz

My Server Version : 1.8.8 Spigot 
My placeholders version : 2.9.2

**Comment by Andre601** [comment]
You use a version of the Player-expansion, that uses 1.9+ methods.
You need to either update your server version, or use an older version of the Player-expansion.

I sadly don't know, what version would be the one for you to use.

Feel free to join our discord, if you need more support: https://helpch.at/discord
