### ISSUE TITLE
Signlink placeholders

### ISSUE THREAD

**Issue by stijnb1234** [help-chat/PlaceholderAPI#3]
**What's the plugin's link?**
https://www.spigotmc.org/resources/signlink.39593/

**Does the plugin use an expansion or build-in placeholders? (If it use an expansion, please note the name of it)**
Build-in placeholders, so no command.

**List the placeholders here, maybe a short description for each too.**
%sl_[variable name]% -> Replace [variable name] with the name of the signlink variabel.

**Comment by Andre601** [comment]
Added it. Sorry for the long delay.
