### ISSUE TITLE
My CountryOnJoin plugin started to support PlaceholderAPI

### ISSUE THREAD

**Issue by KirillBorunov** [help-chat/PlaceholderAPI#4]
### Type
> What kind of request is this? (Multiple selections possible)

- [x] New plugin/expansion that provides placeholders. (Request adding of the plugin to the wiki "Plugin placeholders")
- [ ] Missing plugin that supports PlaceholderAPI. (Request adding of the plugin to "Plugins supporting PlaceholderAPI")

### Plugin
> What is the name of the plugin?

[CountryOnJoin - Bukkit Edition](https://www.spigotmc.org/resources/country-on-join-bukkit-edition.34275/)

### Placeholders/others
> What are the new placeholders/Any additional info?

%countryonjoin_player_country_code% : You can get the country ISO code of a player.
%countryonjoin_player_country_name% : You can get the country name of a player.

**Comment by Andre601** [comment]
Added it to the [Placeholder-list](https://github.com/help-chat/PlaceholderAPI/wiki/Placeholders#country-on-join)
Thank you for supporting PlaceholderAPI!
