### ISSUE TITLE
Adding QuestCreator placeholders to the list

### ISSUE THREAD

**Issue by GuillaumeVDN** [help-chat/PlaceholderAPI#5]
### Type
> What kind of request is this? (Multiple selections possible)

- [x] New plugin/expansion that provides placeholders. (Request adding of the plugin to the wiki "Plugin placeholders")
- [x] Missing plugin that supports PlaceholderAPI. (Request adding of the plugin to "Plugins supporting PlaceholderAPI")

### Plugin
> What is the name of the plugin?

QuestCreator (https://www.spigotmc.org/resources/38734/)

### Placeholders/others
> What are the new placeholders/Any additional info?

New placeholders list : https://github.com/PYRRH4/QuestCreator/wiki#list-of-questcreator-placeholderapi-placeholders

**Comment by Andre601** [comment]
Added the new placeholders to the list (The plugin was already listed as supporting placeholders)

Thanks for supporting PlaceholderAPI
