### ISSUE TITLE
StrikePractice supports PlaceholderAPI

### ISSUE THREAD

**Issue by toppev** [help-chat/PlaceholderAPI#6]
### Type
> What kind of request is this? (Multiple selections possible)

- [ ] New expansion providing placeholders.
- [x] New plugin providing placeholders.
- [x] New plugin supporting PlaceholderAPI.

### Plugin
> What is the name of the plugin/expansion?
> Provide also a link to it.

StrikePractice
https://www.spigotmc.org/resources/46906/
### Placeholders/others
> What are the new placeholders/Any additional info?

All placeholders listed on the page

**Comment by Andre601** [comment]
Can you provide a bit more information on how your placeholders actually work?
Like how is the syntax?

**Comment by toppev** [comment]
Sure.
For example %strikepractice_opponent% for 1v1 opponent's name.
So basically %strikepractice_[the StrikePractice placeholder without < and >]%

All placeholders:
https://pastebin.com/vtBGvpKF

**Comment by Andre601** [comment]
[I added the placeholders](https://github.com/help-chat/PlaceholderAPI/wiki/Placeholders#strikepractice-2)

Thank you for supporting PlaceholderAPI
