### ISSUE TITLE
Placeholder Broken with left/right click requirement

### ISSUE THREAD

**Issue by Metal121** [help-chat/PlaceholderAPI#7]
- %tokenenchant_token_num%  
- %tokenenchant_token%

Plugin: TokenEnchants

The placeholders works in left/right click requirement but if I have over 999 tokens the left/right click requirement don't work, If I have under 999 tokens it works. I saw on the help chat a lot of players had this issue. I'll post my config of what I tried doing https://paste.helpch.at/kagibeweyu.bash

**Comment by Andre601** [comment]
This repository is not for help with placeholders (And especially not with other plugins like DeluxeMenus)

Please join the [help chat](https://helpch.at/discord) discord to receive faster support for your issue. Thanks
